# Generated by Django 4.0.1 on 2022-03-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_selection_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='ads',
            new_name='items',
        ),
    ]
