# Generated by Django 4.0.1 on 2022-03-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_ads_selection_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='items',
            new_name='ad',
        ),
    ]
