# Generated by Django 4.0.1 on 2022-03-29 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_items_selection_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
