# Generated by Django 4.0.1 on 2022-03-29 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_selection_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='owner',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
