# Generated by Django 4.0.1 on 2022-04-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
