# Generated by Django 4.0.1 on 2022-04-24 15:08

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[ads.models.check_birth_date]),
        ),
    ]
